services:
  postgres:
    image: postgres:15
    container_name: postgres15
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - "8888:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./settings/scripts:/scripts
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  orthrus:
    build: ./image
    container_name: orthrus
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_PORT=8888
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    volumes:
      - ./:/home
      - /data1/tbilot/reproduce:/data # should replace /path/of/data/folder as path to the data folder
    entrypoint: bash
    stdin_open: true
    tty: true

volumes:
  postgres_data: