services:
  postgres:
    image: postgres:17
    container_name: postgres
    networks:
      - shared_network
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "${DOCKER_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init-create-empty-databases.sh:/docker-entrypoint-initdb.d/init-create-empty-databases.sh
      - ./settings/scripts:/scripts
      - ${INPUT_DIR:-/data}:/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  shared_network:
    name: shared_network
    labels:
      com.docker.compose.network: shared_network

volumes:
  postgres_data:
    name: postgres_data

